name: pruebabackend
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: javier <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.6.0
  shelf: ^0.7.5
  mysql1: ^0.17.1
 
  rpc: ^0.6.2
  
  http: ^0.12.1

  mime_type: ^0.3.1

  
  
  mime: ^0.9.6+3

  path: ^1.7.0

  http_server: ^0.9.8+3
  


dev_dependencies:
  pedantic: ^1.9.0
