name: pruebabackend
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: javier <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  
  shelf: ^1.2.0
  mysql1: ^0.19.2
 
  http: ^0.13.4

  path: ^1.8.0

  flutter_lints: ^1.0.4

  shelf_web_socket: ^1.0.1
  flutter_socket_io: ^0.6.0
  shelf_router: ^1.1.2
  socket_io: ^1.0.1
  web_socket_channel: ^2.1.0
  dart_jsonwebtoken: ^2.4.0

dev_dependencies:
  # flutter_lints: ^1.0.4
